### ISSUE TITLE
Update example docs

### ISSUE THREAD

**Issue by nicktgr15** [dasebe/webcachesim#5]
Hi, 

I think that the command used in the example is wrong 
```
./webcachesim trace.txt LRU 30 0 10
```
Cheers,
Nick

**Comment by dasebe** [comment]
Yes, you're right, that's old syntax for a previous version.
Correct syntax would be:
    ./webcachesim test.tr 0 LRU 30

**Comment by dasebe** [comment]
We're actually currently working on another revision of the interface and a few new features. If there's interest we can update the code.
In any case, I'll just update the examples.

**Comment by dasebe** [comment]
Updated the examples, and added an example request trace. For now, we're staying with the simple interface.
