### ISSUE TITLE
Not the expected results

### ISSUE THREAD

**Issue by nicktgr15** [dasebe/webcachesim#6]
Hi,

I'm using the tool with the same warmup and traceFile with a very big number for the cacheSizeBytes and I would expect to see an object hit ration of 1.0. However I get something around to 0.37. How is this explained? (using LRU)

Cheers,
Nik

**Comment by dasebe** [comment]
Hi Nik,
are you using one of the trace files from webcachesim, or another trace file? If you provide me with a small trace file to reproduce this behavior, I'm happy to find the cause.

While there can be bugs, there can also be other reasons for low hit ratios, e.g., "one-hit-wonders": objects that are only ever requested once and thus lead to cache misses even if the cache size were infinity.

Daniel

**Comment by dasebe** [comment]
Oh and can you post the exact call parameters you are using? It could also be that my documentation is faulty.

**Comment by dasebe** [comment]
Can someone reproduce this issue?
