### ISSUE TITLE
Tracegenerator has segment fault when the number of unique object too large

### ISSUE THREAD

**Issue by sunnyszy** [dasebe/webcachesim#7]
I got segment fault when using following cmd (seems not so big):
`./basic_trace 3000000 50000 1.8 1 5000000000 test.tr`
If I reduce the unique object size by a factor of 10, the program will be fine:
`./basic_trace 300000 50000 1.8 1 5000000000 test.tr`

**Comment by sunnyszy** [comment]
change line 37 will be fine
`auto * size = new long[no_objs];`

**Comment by dasebe** [comment]
Thank you, Zhenyu. This seems like a good fix.

Would you like to fork and send a pull request, or would you rather have
me fix this?

Daniel

**Comment by sunnyszy** [comment]
You can directly fix that~ Not a big change.

**Comment by dasebe** [comment]
fixed by commit 1cf0e007372c9c723b50f9564aca67148ddb7a3c
